language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - debhelper
      - libblas-dev
      - libfftw3-dev
      - liblapack-dev
      - gfortran
      - libgtest-dev
      - cmake
script: ./autogen.sh && ./configure && make
